"""PDF + markdown report generation for GEO visibility digests."""

from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from . import i18n, queries
from .db import connect

_ENV = Environment(loader=FileSystemLoader(str(Path(__file__).resolve().parent / "templates")))
PERIODS = {"weekly": (7, "每週", "Weekly"), "monthly": (30, "每月", "Monthly")}

_PERIOD_KEY = {"weekly": "weekly", "monthly": "monthly"}

_REPORT_MD = """\
# {brand_name}
## GEO Visibility Report

**Generated:** {date}
**Period:** Last {days} days
**Engines:** {engine_list}

---

## 1. Overview

| Metric | Value |
|--------|------:|
| Brand visibility | **{visibility:.0f}%** |
| Prompts tracked | {prompts_count} |
| Total evaluations | {runs} |
| Total citations | {citations} |
| Last evaluation | {last_run} |
| Competitors tracked | {comp_count} |

---

## 2. Visibility by Prompt

| Prompt | Tags | Runs | Visibility |
|--------|------|-----:|:----------:|
{prompt_table}

---

## 3. Share of Voice

| Brand | Mentions | Share | Avg Position |
|-------|---------:|------:|:-----------:|
{sov_table}

---

## 4. Top Citation Domains

| Domain | Category | Citations |
|--------|----------|----------:|
{domain_table}

## 5. Top Cited Pages

| URL | Domain | Citations |
|-----|--------|----------:|
{url_table}

---

## 6. Engine Distribution

| Engine | Runs | Share |
|--------|-----:|------:|
{engine_table}

---

## 7. Growth Opportunities

Prompts where competitors appear but **{brand_name}** does not:

{gaps_section}
---
*Generated by prism-geo · {date}*
"""


def generate_markdown(tenant_id: int, days: int = 30) -> str | None:
    """Generate a markdown GEO visibility report from prism data."""
    with connect() as conn:
        d = queries.report_data(conn, tenant_id, days)
    if d is None:
        return None
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    last = d["last_run"][:16] if d["last_run"] else "Never"

    prompt_rows = []
    for p in d["prompt_rows"]:
        tags = p["tags"] or ""
        prompt_rows.append(
            f"| {_esc(p['text'][:80])} | {tags} | {p['runs']} | {p['visibility']:.0f}% |")
    prompt_table = "\n".join(prompt_rows) if prompt_rows else "| *(no prompts)* ||||"

    sov_rows = []
    for s in d["sov"]:
        share = (s["mentions"] / d["total_mentions"] * 100) if d["total_mentions"] else 0
        you = " (You)" if s["name"] == d["brand"]["name"] else ""
        sov_rows.append(
            f"| {_esc(s['name'])}{you} | {s['mentions']} | {share:.0f}% | {s['avg_pos']:.1f} |")
    sov_table = "\n".join(sov_rows) if sov_rows else "| *(no data)* |||"

    dom_rows = []
    for dm in d["top_domains"]:
        dom_rows.append(f"| {_esc(dm['domain'])} | {dm['category']} | {dm['n']} |")
    domain_table = "\n".join(dom_rows) if dom_rows else "| *(no data)* ||"

    url_rows = []
    for u in d["top_urls"]:
        url_rows.append(f"| {_esc(u['url'][:80])} | {_esc(u['domain'])} | {u['n']} |")
    url_table = "\n".join(url_rows) if url_rows else "| *(no data)* ||"

    eng_rows = []
    for e in d["engines"]:
        share = (e["n"] / d["runs"] * 100) if d["runs"] else 0
        eng_rows.append(f"| {_esc(e['name'])} | {e['n']} | {share:.0f}% |")
    engine_table = "\n".join(eng_rows) if eng_rows else "| *(no data)* |"

    if d["gaps"]:
        gap_lines = []
        for g in d["gaps"]:
            gap_lines.append(
                f"- **{_esc(g['text'][:80])}** — competitors present: {g['competitors']}")
        gaps_section = "\n".join(gap_lines)
    else:
        gaps_section = "*(No gaps found — your brand appears in all tracked prompts.)*"

    engine_names = [e["name"] for e in d["engines"]]
    engine_list = ", ".join(engine_names) if engine_names else "None"

    return _REPORT_MD.format(
        brand_name=_esc(d["brand"]["name"]),
        date=now, days=d["days"], engine_list=engine_list,
        visibility=d["visibility"], prompts_count=d["prompts_count"],
        runs=d["runs"], citations=d["citations"], last_run=last,
        comp_count=len(d["competitors"]),
        prompt_table=prompt_table, sov_table=sov_table,
        domain_table=domain_table, url_table=url_table,
        engine_table=engine_table, gaps_section=gaps_section,
    )


def _esc(s: str) -> str:
    return s.replace("|", "\\|")


# --- PDF generation (existing) ---


def generate(tenant_id: int, tenant_name: str, brand_name: str,
             period: str, model_id: int | None = None, lang: str = "en") -> bytes:
    from weasyprint import HTML
    days, _, _ = PERIODS.get(period, PERIODS["monthly"])
    with connect() as conn:
        data = _build_data(conn, tenant_id, days, model_id)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    period_key = _PERIOD_KEY.get(period, "monthly")
    period_label = i18n.t(lang, period_key)

    model_name = data["model_name"]
    if model_name == "All models":
        model_name = i18n.t(lang, "all_models")

    def t(key, **fmt):
        return i18n.t(lang, key, **fmt)

    html_str = _ENV.get_template("report.html").render(
        lang=lang,
        t=t,
        generated_at=now,
        brand_name=brand_name,
        period_label=period_label,
        data={**data, "model_name": model_name},
    )
    return HTML(string=html_str).write_pdf()


def _build_data(conn, tenant_id: int, days: int, model_id: int | None) -> dict:
    vis = queries.visibility_page(conn, tenant_id, days, model_id)
    sov = queries.share_of_voice_page(conn, tenant_id, days, model_id)
    cit = queries.citations_page(conn, tenant_id, days, model_id)

    mention_count = sum(c["runs"] for c in vis.get("cards", []))
    model_name = "All models"
    if model_id:
        row = conn.execute("SELECT name FROM models WHERE id = ?", (model_id,)).fetchone()
        if row:
            model_name = row["name"]

    return {
        "overall": vis["overall"],
        "prompt_count": vis["prompt_count"],
        "run_count": vis["run_count"],
        "mention_count": mention_count,
        "cards": vis["cards"],
        "sov": sov.get("table", []),
        "citations": cit.get("top_domains", []),
        "model_name": model_name,
    }
